/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as icoSol from "./Ico.sol";
export type { icoSol };
export type { SpaceCoin } from "./SpaceCoin";
export type { SpaceLP } from "./SpaceLP";
export type { SpaceRouter } from "./SpaceRouter";
