/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as icoSol from "./Ico.sol";
export { SpaceCoin__factory } from "./SpaceCoin__factory";
export { SpaceLP__factory } from "./SpaceLP__factory";
export { SpaceRouter__factory } from "./SpaceRouter__factory";
