/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ICO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICO__factory>;
    getContractFactory(
      name: "SpaceCoin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SpaceCoin__factory>;
    getContractFactory(
      name: "SpaceLP",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SpaceLP__factory>;
    getContractFactory(
      name: "SpaceRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SpaceRouter__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ICO",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICO>;
    getContractAt(
      name: "SpaceCoin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SpaceCoin>;
    getContractAt(
      name: "SpaceLP",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SpaceLP>;
    getContractAt(
      name: "SpaceRouter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SpaceRouter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
